version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    restart: always 