version: '3.8'

services:
  weather-api:
    build: .
    container_name: weather-api
    ports:
      - "8000:8000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs 