version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  api:
    image: chipekve/weather-api-service-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always

  bot:
    image: chipekve/weather-api-service-bot:latest
    ports:
      - "8080:8001"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://api:8000
      - REDIS_URL=redis://redis:6379
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=8001
    depends_on:
      - api
      - redis
    restart: always

volumes:
  redis_data: 