version: '3.8'

services:
  api:
    image: chipekve/weather-api-service-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    restart: always

  bot:
    image: chipekve/weather-api-service-bot:latest
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    restart: always 