name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Create data directory for SQLite
      run: mkdir -p data

    - name: Set permissions for data directory
      run: chmod 777 data
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: chipekve/weather-api-service-api:latest
    - name: Build and push Bot image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.bot
        push: true
        tags: chipekve/weather-api-service-bot:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /root/weather-api-service
          git pull origin main
          docker pull chipekve/weather-api-service-api:latest
          docker pull chipekve/weather-api-service-bot:latest
          docker-compose down
          docker-compose up -d
          docker system prune -f
          echo "✅ Развертывание завершено!" 